const images = {
	upload: '/assets/images/upload.svg',
	link: '/assets/images/link.svg',
	backwithletter: '/assets/images/backwithletter.svg',
	addform: '/assets/images/addform.svg',
	addform_hover: '/assets/images/addform_hover.svg',
	removeform: '/assets/images/removeform.svg',
	removeform_hover: '/assets/images/removeform_hover.svg',
	paging_dot_dark: '/assets/images/paging_dot_dark.svg',
	paging_dot_medium: '/assets/images/paging_dot_medium.svg',
	search: '/assets/images/search.svg',
	search_b: '/assets/images/search-b.svg',
	trash: '/assets/images/trash.svg',
	trash_r: '/assets/images/trash-r.svg',
	dashboard: '/assets/images/dashboard.svg',
	home: '/assets/images/home.svg',
	researcher: '/assets/images/researcher.svg',
	event: '/assets/images/event.svg',
	project: '/assets/images/project.svg',
	insight: '/assets/images/insight.svg',
	newsletter: '/assets/images/newsletter.svg',
	orcagroup: '/assets/images/orcagroup.svg',
	up_w: '/assets/images/up-w.svg',
	up_b: '/assets/images/up-b.svg',
	down_w: '/assets/images/down-w.svg',
	down_b: '/assets/images/down-b.svg',
	download: '/assets/images/download.svg',
	add: '/assets/images/add.svg',
	add_h: '/assets/images/add-h.svg',
	sub: '/assets/images/sub.svg',
	sub_h: '/assets/images/sub-h.svg',
	back: '/assets/images/back.svg',
	next: '/assets/images/next.svg',
	previous: '/assets/images/previous.svg',
	reload: '/assets/images/reload.svg',
	checkbox: '/assets/images/checkbox.svg',
	smallcalendar: '/assets/images/smallcalendar.svg',
	pen_b: '/assets/images/pen-b.svg',
	pen_w: '/assets/images/pen-w.svg',
};

export default images;
