const images = {
	upload: '/assets/images/upload.svg',
	link: '/assets/images/link.svg',
	backwithletter: '/assets/images/backwithletter.svg',
	addform: '/assets/images/addform.svg',
	paging_dot_dark: '/assets/images/paging_dot_dark.svg',
	paging_dot_medium: '/assets/images/paging_dot_medium.svg',
	search: '/assets/images/search.svg',
	trash: '/assets/images/trash.svg',
	dashboard: '/assets/images/dashboard.svg',
	home: '/assets/images/home.svg',
	researcher: '/assets/images/researcher.svg',
	event: '/assets/images/event.svg',
	project: '/assets/images/project.svg',
	insight: '/assets/images/insight.svg',
	newsletter: '/assets/images/newsletter.svg',
	orcagroup: '/assets/images/orcagroup.svg',
	up_w: '/assets/images/up-w.svg',
	down_w: '/assets/images/down-w.svg',
	down_b: '/assets/images/down-b.svg',
	download: '/assets/images/download.svg',
	add: '/assets/images/add.svg',
	back: '/assets/images/back.svg',
	next: '/assets/images/next.svg',
	previous: '/assets/images/previous.svg',
	reload: '/assets/images/reload.svg',
	checkbox: '/assets/images/checkbox.svg'
};

export default images;
